# Comments

## Create an comment

POST http://localhost:8000/api/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3NWYyOGI0OTY1YjY5MzI0ODllMGZjMCIsInVzZXJuYW1lIjoidmxhZCIsImVtYWlsIjoidmxhZEBtYWlsLmNvbSIsImlhdCI6MTczNjg4MDA1MywiZXhwIjoxNzM3MDUyODUzfQ.FFHarfUEwVpUE_q3QOqtQU2NUYlP5_O45vudtMgmPhI

{
  "text": "Comment text",
  "rating": 4,
  "offerId": "675f2838bb5d19ed14199ad6",
  "authorId": "675f2838bb5d19ed14199abe"
}
