# Cities

## Create a new city

POST http://localhost:8000/api/cities HTTP/1.1
Content-Type: application/json

{
  "name": "Amsterdam",
  "location": {
    "coordinates": [52.37454, 4.897976]
  }
}

###

## Get all cities

GET http://localhost:8000/api/cities HTTP/1.1

###
