# Users

## Create a new user
POST http://localhost:8000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@mail.com",
  "type": "pro",
  "avatarUrl": "https://www.example-image.com",
  "password": "12345678"
}

###
