# Users

## Create a new user
POST http://localhost:8000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "vlad",
  "email": "vlad@mail.com",
  "password": "12345678",
  "passwordConfirmation": "12345678"
}

###

## Login

POST http://localhost:8000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "vlad@mail.com",
  "password": "12345678"
}

###

## Auth

GET http://localhost:8000/api/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3NWYyOGI0OTY1YjY5MzI0ODllMGZjMCIsInVzZXJuYW1lIjoidmxhZCIsImVtYWlsIjoidmxhZEBtYWlsLmNvbSIsImlhdCI6MTczNjg2ODcwNSwiZXhwIjoxNzM3MDQxNTA1fQ.rOlxowh1-9vhdkx8uH-fizzedmhNfwJttjD-TrZxq7Q

###
